### ISSUE TITLE
Shooting interactables doesn't take into account where the bullet actually lands.

### ISSUE THREAD

**Issue by Clark919** [IkaOverride/ShootingInteractions#1]
Not sure if this is an intended feature or not, but from testing I've noticed it's very easily repeatable to fully sprint and jump and still accurately hit a door's button, triggering it. This of course isn't where the bullet actually lands as a decal can be painted on the wall next to where the button you supposedly hit is.

As an example, see the image attached. Although the reticle indicates the bullet will land somewhere within the region, it will always trigger the button provided it is in the center of the crosshairs. This creates some pretty annoying run-and-gun door opening mechanics even with the worst guns, which is why I'm bringing this issue up.

![image](https://github.com/SiphoxR/ShootingInteractions/assets/44264851/21399db4-bf92-4835-a96e-e51311e6e291)

**Comment by ghost** [comment]
Hello! Yes this is an intended feature, there are multiple reasons why I decided to do this, most noticeably to allow players to have more control over the things you shoot at, otherwise it could become quickly annoying, and also the fact that when I made this plugin, the exiled event I could use to make it take into account where the bullet really lands did not work with some weapons (but this is not an issue anymore).
I will keep this issue up because I might add an option in the config file to change this in the near future.

**Comment by ghost** [comment]
Done. Will be in next release.

**Comment by ghost** [comment]
Just released 2.2.0 with the accurate bullets feature.
